### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by fordp2002** [richard42/CoCo3FPGA#1]
Great to find Coco3 on Github can you add a getting started Read me to help me trying it on my DE1?

**Comment by richard42** [comment]
Sorry, I don't have plans to put together a step-by-step guide for using this any time soon.  It's pretty complicated to build and load and run this thing.  I agree it would be nice to have more documentation but I really don't have the time to put it together now.  I would suggest visiting the COCO3FPGA group on Yahoo and asking questions there to get it running.  It's not too bad if you want to just copy the pre-built SOF files but building from source is a little more complicated.  One thing that I did discover is that it doesn't work right if you build with the Linux version of the Altera Quartus software.  You need to use the Windows version.
